baseURL = "https://newerkey.github.io/portfolio-engine/"
languageCode = 'en-us'
title = 'Yvette Nartey'
theme = "PaperMod"


[params]
    defaultTheme = "light"
    env = "production"
    description = "Infrastructure Support Engineer | Digital Garden"

# Minimalist Layout Settings
[params.assets]
    disableHLJS = true 

# HomePage 
[params.profileMode]
    enabled = true
    title = "Yvette Nartey" 
    subtitle = "Supporting and Building reliable platforms. Automating the rest where necessary."


    [[params.profileMode.buttons]]
      name = "Projects"
      url = "/projects"
    [[params.profileMode.buttons]]
      name = "Notes"
      url = "/notes"

# Main Menu (Simple)
[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 10
[[menu.main]]
  identifier = "notes"
  name = "Notes"
  url = "/notes/"
  weight = 20